<?php

/*********************************************************************
* Extension configuration file for ext "svconnector_feed".
*
* Generated by ext 02-05-2016 09:27 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Connector service - FEED',
  'description' => 'Connector service for XML files or RSS feeds',
  'category' => 'services',
  'version' => '2.0.0',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'clearcacheonload' => 1,
  'author' => 'Francois Suter (Cobweb)',
  'author_email' => 'typo3@cobweb.ch',
  'author_company' => '',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '7.6.0-7.99.99',
      'svconnector' => '3.0.0-0.0.0',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  '_md5_values_when_last_written' => 'a:17:{s:9:"ChangeLog";s:4:"56f3";s:11:"LICENSE.txt";s:4:"6404";s:10:"README.txt";s:4:"4f8f";s:13:"composer.json";s:4:"5ce8";s:21:"ext_conf_template.txt";s:4:"ef02";s:12:"ext_icon.png";s:4:"1813";s:17:"ext_localconf.php";s:4:"3c46";s:33:"Classes/Service/ConnectorFeed.php";s:4:"131b";s:26:"Documentation/Includes.txt";s:4:"c83c";s:23:"Documentation/Index.rst";s:4:"72b0";s:25:"Documentation/Targets.rst";s:4:"cc7b";s:37:"Documentation/Configuration/Index.rst";s:4:"b9c5";s:33:"Documentation/Developer/Index.rst";s:4:"5fa7";s:36:"Documentation/Installation/Index.rst";s:4:"c6c0";s:36:"Documentation/Introduction/Index.rst";s:4:"ec63";s:40:"Resources/Private/Language/locallang.xlf";s:4:"957e";s:42:"Resources/Public/Samples/Configuration.txt";s:4:"d799";}',
  'comment' => 'Verified compatibility with TYPO3 CMS 7; moved to namespaces.',
  'user' => 'francois',
);

?>